name = "Niva"
grammar = "scala"
path_suffixes = ["niva", "sc", "scala"]
line_comments = ["// "]
autoclose_before = ";:.,=}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "/*", end = " */", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
# collapsed_placeholder = " /* ... */ "
# scope_opt_in_language_servers = ["tailwindcss-language-server"]

# [overrides.string]
# word_characters = ["-"]
# opt_into_language_servers = ["tailwindcss-language-server"]
